blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.all_blogs, name='all_blogs'),
        path('<int:blog_id>', views.details, name="details")
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', views.home, name="home" ),
    path('about/',views.about, name="about"),
    path('blog/', include('blog.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/models.py
from django.db import models


class Blogs(models.Model):
    title: str = models.CharField(max_length=100)
    date = models.DateField()
    description = models.TextField(max_length=300)

    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models


class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=200)
    image = models.ImageField(upload_to='blog/images')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from .models import Blogs


def all_blogs(request):
    blogs = Blogs.objects.order_by('-date')[:5]
    return render(request, 'blogs/all_blogs.html', {'blogs': blogs})


def details(request, blog_id):
    blogs = get_object_or_404(Blogs, pk=blog_id)

    return render(request, 'blogs/each_blog.html', {'blogs':blogs})

portfolio/views.py
from django.shortcuts import render
from .models import Project
def home(request):
    projects = Project.objects.all()
    return render(request, 'portfolio/home.html', {'Projects': projects})


def about(request):
    return render(request, 'portfolio/about.html')

blog/templates/blogs/all_blogs.html
{% extends 'portfolio/base.html' %}
{% block title %}
        Blogs
{% endblock %}
{% block content %}
    <h2>There are {{ blogs.count }} number of blog{{ blogs.count|pluralize }}</h2>
    {% load static %}
    <img src="{% static 'blog/convo12.JPG' %}" alt="">

    {% for blog in blogs %}
        <a href="{% url 'blog:details' blog.id %}"><h1>{{ blog.title }}</h1></a>
        <p>{{ blog.date| date:"M d Y"| upper }}</p>
        <p>{{ blog.description|striptags|truncatechars:70 }}</p>
    {% endfor %}

{% endblock %}

blog/templates/blogs/each_blog.html
{% extends 'portfolio/base.html' %}
{% block title %}
        Each blog
{% endblock %}
{% block content %}
    <div>

        <h2>{{ blogs.title }}</h2>
        <h3>{{ blogs.date| date:"F jS Y"| upper }}</h3>
        <p>{{ blogs.description|safe }}</p>

    </div>
{% endblock %}

portfolio/templates/portfolio/about.html
{% extends 'portfolio/base.html' %}
{% block title %}
        About
{% endblock %}


{% block content %}
        <h1>About Page</h1>
{% endblock %}

portfolio/templates/portfolio/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% load static %}
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
          integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
<!-- Icon CSS -->
    <link rel="icon" type="image/png" href="{% static 'portfolio/logo.png' %}">
<!-- Custom style CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body class="container-fluid">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">
    <img src="{% static 'portfolio/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
    Weather boy
  </a>
 <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'about' %}">
                  About
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% static 'portfolio/WEKA.pdf' %}">
                  Weka files
                </a>
            </li>
            <li class="nav-item">
                <a  class="btn btn-primary" href="{% url 'blog:all_blogs' %}">
                  Blog
                </a>
            </li>
        </ul>
</nav>
    {% block content %}



    {% endblock %}


<!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns"
        crossorigin="anonymous"></script>

<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
-->
</body>
</html>

portfolio/templates/portfolio/home.html
{% extends 'portfolio/base.html' %}
{% block title %}
        Home
{% endblock %}
{% block content %}
<a href="{% url 'blog:all_blogs' %}">All blogs</a>
{% load static %}


    <div class="text-center">
        <img class="rounded mx-auto image " src="{% static 'portfolio/collins.jpg' %}" alt="">

    </div>

    <div>


        <br>
        <div class="row">
               {% for project in Projects %}
            <div class="col-4">
               <h2>{{ project.title }}</h2>
            <p>{{ project.description }}</p>
            <img src="{{ project.image.url }}">

            {% if project.url %}
                <a href="{{ project.url }}">Link</a>
            {% endif %}
            </div>
             {% endfor %}
        </div>






    </div>

{% endblock %}